compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[[kv_namespaces]]
id = "36ecbf531eeb440e84daeda4c4e6e905"
preview_id = "3486333f34994a8999e0d097cef04c66"
binding = "KV"
